"""Modern package facade for the VSE simulation library."""

from .data_classes import Method, SideTally, Tallies
from .dataframe import rows_to_dataframe, summarize_vse
from .methods import (
    IRNR,
    V321,
    Borda,
    BulletyApprovalWith,
    Irv,
    IrvPrime,
    Mav,
    Mj,
    Plurality,
    Rp,
    Schulze,
    Score,
    Srv,
)
from .simulation import CsvBatch, allSystems, baseRuns, markMethods, medianRuns, uniquify
from .strategies import (
    Chooser,
    LazyChooser,
    OssChooser,
    ProbChooser,
    beHon,
    beStrat,
    beX,
    biasedMediaFor,
    biaserAround,
    fuzzyMediaFor,
    orderOf,
    skewedMediaFor,
    topNMediaFor,
    truth,
)
from .voter_models import (
    DeterministicModel,
    DimElectorate,
    DimModel,
    DimVoter,
    Electorate,
    KSElectorate,
    KSModel,
    PersonalityVoter,
    PolyaModel,
    QModel,
    RandomModel,
    ReverseModel,
    Voter,
)

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "Borda",
    "BulletyApprovalWith",
    "Chooser",
    "CsvBatch",
    "DeterministicModel",
    "DimElectorate",
    "DimModel",
    "DimVoter",
    "Electorate",
    "IRNR",
    "Irv",
    "IrvPrime",
    "KSElectorate",
    "KSModel",
    "LazyChooser",
    "Mav",
    "Method",
    "Mj",
    "OssChooser",
    "PersonalityVoter",
    "Plurality",
    "PolyaModel",
    "ProbChooser",
    "QModel",
    "RandomModel",
    "ReverseModel",
    "Rp",
    "Schulze",
    "Score",
    "SideTally",
    "Srv",
    "Tallies",
    "V321",
    "Voter",
    "allSystems",
    "baseRuns",
    "beHon",
    "beStrat",
    "beX",
    "biasedMediaFor",
    "biaserAround",
    "fuzzyMediaFor",
    "markMethods",
    "medianRuns",
    "orderOf",
    "rows_to_dataframe",
    "skewedMediaFor",
    "summarize_vse",
    "topNMediaFor",
    "truth",
    "uniquify",
]
